# Generated by Django 6.0 on 2026-02-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_response',
            field=models.TextField(blank=True),
        ),
    ]
