# Generated by Django 6.0 on 2026-02-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_ai_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
