# Generated by Django 6.0 on 2026-02-02 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_ai_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ai_response',
        ),
    ]
