# Generated by Django 6.0 on 2026-02-10 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
